project:
  name: eventbridge-integration-solution-auth0-visualization
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
  s3_bucket: ''

tests:
  eventbridge:
    s3_bucket: ''
    template: ./packaged.yml